- hosts: localhost
  connection: local
  tasks:
  - name: Create VM
    azure_rm_virtualmachine:
      resource_group: rg1
      name: vm1
      vm_size: Standard_B1s
      admin_username: vmatsuda
      ssh_password_enabled: false
      ssh_public_keys:
        - path: /home/vmatsuda/.ssh/authorized_keys
          key_data: "Public Key Here !! ex: id_rsa.pub" 
      network_interfaces: nic1
      managed_disk_type: Standard_LRS
      image:
         offer: 0001-com-ubuntu-server-focal
         publisher: canonical
         sku: 20_04-lts-gen2
         version: latest
      
