- hosts: localhost
  connection: local
  tasks:
  - name: Remove a VM and all resources that were autocreated
    azure_rm_virtualmachine:
      resource_group: rg1
      name: vm1
      state: absent
