- hosts: [localhost]
  connection: local
  tasks:
   - name: Delete public IP address
     azure_rm_publicipaddress:
       name: pip1
       resource_group: rg1
       allocation_method: Static
       state: absent
