- hosts: [localhost]
  connection: local
  tasks:
    - name: Create resource group
      azure_rm_resourcegroup:
        name: rg1
        location: eastus
    - name: Create VNET(Virtual Network)
      azure_rm_virtualnetwork:
        resource_group: rg1
        name: vnet1
        address_prefixes: "10.0.0.0/16"
    - name: Create SUBNET in VNET
      azure_rm_subnet:
        resource_group: rg1
        name: frontendsubnet
        address_prefix: "10.0.1.0/24"
        virtual_network: vnet1
    - name: Create SUBNET in VNET
      azure_rm_subnet:
        resource_group: rg1
        name: backendsubnet
        address_prefix: "10.0.2.0/24"
        virtual_network: vnet1
    - name: Create a NSG(Network Security Group with some rules)
      azure_rm_securitygroup:
         resource_group: rg1
         name: nsg1
         purge_rules: yes
         rules:
           - name: 'AllowSSH'
             protocol: Tcp
             source_address_prefix: 'seuip'
             destination_port_range: 22
             access: Allow
             priority: 100
             direction: Inbound
    - name: Create public IP address
      azure_rm_publicipaddress:
         resource_group: rg1
         allocation_method: Static
         name: pip1
    - name: Create virtual network interface card
      azure_rm_networkinterface:
         name: nic1
         resource_group: rg1
         virtual_network: vnet1
         subnet: frontendsubnet
         public_ip_name: pip1
         security_group: nsg1
    - name: Create VM
      azure_rm_virtualmachine:
         resource_group: rg1
         name: vm1
         vm_size: Standard_B1s
         admin_username: vmatsuda
         ssh_password_enabled: false
         ssh_public_keys:
           - path: /home/vmatsuda/.ssh/authorized_keys
             key_data: "Public Key Here !!! Ex: id_rsa.pub "
         network_interfaces: nic1
         managed_disk_type: Standard_LRS
         image:
           offer: 0001-com-ubuntu-server-focal
           publisher: canonical
           sku: 20_04-lts-gen2
           version: latest 
